# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c9710a58aa7cf2fc162c6c2d7c572d3c9747e1ed8aa82b40de9202a74c192a7ce860cd54edc0caa11690a5a44ed3f7d8419400b8be899c9350bfa78c3e40ee

test:
  secret_key_base: 68478aeda34cde18ca7ba5115b2ab5bdcc6e0a99b08887b19edc4c399ec56a83299542238ff216cfd7850330aab2d5aba138759031045e9aebc1501d495377ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
